### PR TITLE
Classes

### PR DESCRIPTION
**Pull request by kasiasieradzka**

### CODE REVIEW

**Comment by Kasperice** [comment]
I understand that files from "classes" directory should be merged?

**Comment by kasiasieradzka** [comment]
But first we have to check it.

**Comment by kasiasieradzka** [comment]
@Kasperice, ok let's merge it then I will help you with conflicts.

**Comment by Kasperice** [comment]
@kasiasieradzka ok, I will do this in 2h, in case of questions I will ask on Discord, ok?

**Comment by Kasperice** [comment]
It was merged under another PR

**Pull request closed without merging**
